### PR TITLE
[Events] Responsive design polish and bug fixes

### PR DESCRIPTION
**Pull request by rkdavidson**
# Changes

### Basecamp todos addressed
- [**🔥 [Chat] Update copy on offline state**](https://3.basecamp.com/3926363/buckets/17566548/todos/3049860513)
- [**🔥 [Bug] Unable to load an Event Chat**](https://3.basecamp.com/3926363/buckets/17566548/todos/3061631315)
- [**🔥 [Events] Better handle responsive mobile web view**](https://3.basecamp.com/3926363/buckets/17566548/todos/3058078474)
- [**🔥 [Events] Move Calls to Action out of the Panel**](https://3.basecamp.com/3926363/buckets/17566548/todos/3058078478)
- [**🏕 [Events] Animate live indicator for extra "live" feel**](https://3.basecamp.com/3926363/buckets/17566548/todos/3050194849)
- [**🏕 [Chat] useEffect for initializing chat fires back-to-back**](https://3.basecamp.com/3926363/buckets/17566548/todos/3057764922) _(attempted to fix)_
### Additional Changes
- Lots of refinement/polish to padding etc for better mobile/tablet experience
- Add `<GridContainer>` , `<Row>`, `<Col>` components and uses them in the new Events components
  - These are simple wrappers for Bootstrap classes, intended to improve code readability
- Add `breakpoint` utility and media query breakpoints from Bootstrap to `styled-components` theme
- In a few places, adds lodash `get` to reduce chance of unexpected Rock/API data from crashing page

# Tradeoffs/Caveats
Responsive layout for the `<EventPanel>`, the side view with **Schedule** and **Chat** tabs, is still clunky on device/orientation combinations like landscape phone and portrait tablet.
In general, this PR focuses on at least _having those elements visible and usable_, and I expect to have to make another smaller pass to further refine most likely after launch. IMO, current state is not release blocking.

I attempted to fix an intermittent bug that occurs when logging in while on a live event. I'm not 100% confident I "truly" fixed it, as it seems slightly quirky and like a potential async race condition when Stream client disconnects and reinitializes.
My attempted fix is to `await` the `StreamChatClient.disconnect()` call in the `useEffect`'s cleanup function, hoping it won't proceed to next effect invocation until it's done cleaning up 🤷‍♂️.

# Test Instructions
- 🔸 Verify the "chat offline" state copy by viewing any event that isn't currently live
- 🔸 Verify the empty chat state (live, but no messages) by hard-coding `'dev-empty-channel'` in place of `channelId` on `src/content-single/EventContentItem/components/EventChat.js::132`
- 🔸 Verify that you don't get an error when logging in on a live event, after loading the page in a logged out state
- 🔸 Verify general design/layout looks decent across 

# Screenshots

|🎥 <a href="https://www.loom.com/share/9c1bac5b3ecf4f26a279cb57b693feba">Loom Video Overview</a>|
|---|
|<a href="https://www.loom.com/share/9c1bac5b3ecf4f26a279cb57b693feba"></a>|

|Size|Screenshot|
|---|---|
|iPhone X||
|Small-ish Tablet||
|Compressed Desktop/Almost Tablet||
|Desktop||
|X-Large Desktop||

#### Chat List States
|Offline/Not Live|Live, but Empty|
|---|---|
|||

# Tests
- [ ] needed snapshots updated
- [ ] mobile tested
- [ ] latest update from master

### CODE REVIEW

**Comment by jordanwade** [comment]
@rkdavidson for the "Verify that you don't get an error when logging in on a live event, after loading the page in a logged out state". I'm consistently getting an error when trying to login on a live event `Unhandled Rejection (Error): Call setUser or setAnonymousUser before creating a channel`. Is that address in this PR or is it a separate issue unrelated to your work?

image

**Comment by jordanwade** [comment]
For the responsive side of things I feel pretty good with what you have here. Personally, I would rip out bootstrap and use CSS grid for all the layout of this page. It would be a lot easier moving pieces around. I am a bit biased since I've never cared much for bootstrap. 🙂

**Comment by jordanwade** [comment]
@rkdavidson I think you might be ok. So, I'm hitting production rock and when I use my legit login with my phone number no error. When I try my junk/test `Barry Allen` login I get the error, is it possible there is some feature flag related issue since my Barry Allen user is not in the security group on Production Rock?

**Comment by rkdavidson** [comment]
@jordanwade Oh good to know. Yeah, you're on to something. It's strange though, because as the test `yoda@jedi.order`:`yoda` user I get the error _intermittently_ (but frequently), but never as my ryan@differential.com one.

I'll look into better error handling. I may be assuming the token fetch step was valid if _any_ data came back — even if the `streamChatToken` is null.

**Review by jordanwade — APPROVED** [review]

**Pull request merged**
