### PR TITLE
[CFDP-932] added Dream Teams to groups

### PR DESCRIPTION
**Pull request by dzwood**
# Related Issue
- Added the ability to view **my Dream Teams**. 
- By going to `/dream-teams` a user can log in to view their Dream Teams and also view the details for that group[CFDP-934], and/or a user can search for a new Dream Team[CFDP-933].

# Changes or Updates
- added **DreamTeams** to `group`
- added **DreamTeams** to `router`

# Tests
- [x] needed snapshots updated
- [x] mobile tested
- [x] latest update from master

[CFDP-934]: https://christfellowshipchurch.atlassian.net/browse/CFDP-934
[CFDP-933]: https://christfellowshipchurch.atlassian.net/browse/CFDP-933

### CODE REVIEW

**Comment by rkdavidson** [comment]
@dzwood and @asleepingpanda, WDYT about this PR?

Is there value in the interim of the web-v2 migration? Should we close?

**Comment by dzwood** [comment]
@rkdavidson this PR is probably not relevant anymore, I updated it to master though. I'm gonna check with the team today to see if this is something we still want.

**Comment by rkdavidson** [comment]
Sounds good, @dzwood . Feel free to **Close with comment** later after you touch base with the team.

**Comment by rkdavidson** [comment]
Closing due to inactivity and impending web-v2 launch.

**Pull request closed without merging**
