### PR TITLE
[CFDP-939] Hide campus address when no service times

### PR DESCRIPTION
**Pull request by dzwood**
# Changes or Updates
- Updated the `CampusSelect` component to hide address when no service times are available, and added a replacement text instead.

# Tests
- [x] needed snapshots updated
- [x] mobile tested
- [x] latest update from master

### CODE REVIEW

**Comment by rkdavidson** [comment]
Hey @dzwood , FYI there is a temporary fork/duplicate of `<CampusSelect>` and `<EventSchedule>` that, ideally, can replace the existing ones one we're ready to release the LiveStream Events Chat work.

For `<EventSchedule>`, I decomposed some of the sub-components in there to a separate file.

Apologies for the inconvenience in the mean time, I wasn't expecting to have these dupes live this long/didn't anticipate overlap with other work 😪.
LMK if you have any questions parsing what's where or the appropriate place to make these changes.

**The duplicates are:**
- [src/content-single/EventContentItem/components/CampusSelector.js](https://github.com/christfellowshipchurch/web-app/blob/master/src/content-single/EventContentItem/components/CampusSelector.js)
- [src/content-single/EventContentItem/components/EventSchedule.js](https://github.com/christfellowshipchurch/web-app/blob/master/src/content-single/EventContentItem/components/EventSchedule.js)
- [src/content-single/EventContentItem/components/EventScheduleConnected.js](https://github.com/christfellowshipchurch/web-app/blob/master/src/content-single/EventContentItem/components/EventScheduleConnected.js)
- [src/content-single/EventContentItem/components/EventScheduleTimes.js](https://github.com/christfellowshipchurch/web-app/blob/master/src/content-single/EventContentItem/components/EventScheduleTimes.js)

**Comment by dzwood** [comment]
Hey @rkdavidson so sorry for just getting to this now, I'm not sure if I fully understand the issue with `<CampusSelect/>` and `<EventSchedule/>` correctly. But I'm open to just using your changes that you made for the **EventContentItem**, the two PRs I have are pretty minor changes. You already merged LiveStreams Events Chat, so I can just update from master? Let me know what you think.

**Comment by rkdavidson** [comment]
Yeah, it's a bit tricky to think about in the interim and apologies for not being more clear communicating this up front — didn't expect the limbo/intermediate period between creating a `sandbox` version of the **Events** page and releasing it to last this long.

Tried to quickly mock up the timeline/situation, hoping it makes it a bit clearer:
image

If we merge these two PRs as they are, the changes will get overwritten when we release the new **Events** page (which is currently `src/content-single/EventContentItem/index.sandbox.js`) — since that 👈 page uses different components than the existing `index.js`.

Today, users still see the "old" **Events** page, so they would see these fixes if we merge the PRs.
But unless we _also_ make the changes in the new components used by `EventContentItem/index.sandbox.js`, they'll get overwritten soon.

**So I suggest we leave the current PRs as is, but _also_ add these fixes to the new (duplicated) components mentioned in [my other comment](https://github.com/christfellowshipchurch/web-app/pull/179#issuecomment-709571004).
That way we fix the problem for users _now_, _and_ the future.

Does that help clarify?
Again, sorry this is so confusing!

**Comment by dzwood** [comment]
@rkdavidson Ahhh gotcha, yes this totally makes sense now. You're totally fine, thank you for explaining so well! I'll go head and apply these changes to the `sandbox` version since that is the one we will be using. 

Do we know when we plan on moving the new Events pages to production? I'll add the changes to the other components first, but I might ask we also just merge these to master while were waiting and still using the old Events pages.

**Comment by rkdavidson** [comment]
Yeah good question, we'll need to get this [Event Chat/Schema](https://github.com/christfellowshipchurch/apollos-api/pull/132)  PR merged on the API side but it'll require some regression testing and Rock updates IIRC.

We'll chat with @asleepingpanda about it when he's back from vacation.

But I agree, let's just add the changes you made in this PR to the duplicated/extra version of the component over here:
https://github.com/christfellowshipchurch/web-app/blob/master/src/content-single/EventContentItem/components/CampusSelector.js

That way it'll fix old and new in the mean time.
Same principle apples to the Add to Calendar one — I'm not familiar with the original ticket/thing being fixed with these changes, but doesn't look like it'll be difficult to translate/mirror the changes to both places.

**Comment by dzwood** [comment]
@rkdavidson I added the changes to the `sandbox` file for the **CampusSelect** as well, so the changes to hide address on the campus pages should reflect on the `sandbox` version as well when testing the new Event items and shouldn't affect anything else. 

I think this should cover any overlapping issues with the new Events when we merge them and while also taking care of the [campus pages](https://deploy-preview-179--christfellowshipchurch.netlify.app/locations/boca-raton) we're trying to update. 

I think we'll have to eventually re think on how we build/use the **CampusSelect**, since it's being used in so many areas. But I feel like this should be good for now. I'm gonna be working on it more as I work on updating the RSVP form, just wanted to get this PR merged first before I start getting into it. Let me know if you have any concerns or comments!

**Review by rkdavidson — APPROVED** [review]

**Pull request merged**
